### ISSUE TITLE
training fails at the end when with-tracking is false 

### ISSUE THREAD

**Issue by Ben-Epstein** [arcee-ai/DALM#46]
```
dalm train-rag-e2e \
"qa-outputs/question_answer_pairs.csv" \
"BAAI/bge-large-en" \
"meta-llama/Llama-2-7b-hf" \
--dataset-passage-col-name text \
--output-dir "rag_e2e_checkpoints" \
--no-with-tracking \
--per-device-train-batch-size 12
```

or 
```
python ../dalm/training/rag_e2e/train_rage2e.py \
  --dataset_path "qa-outputs/question_answer_pairs.csv" \
  --retriever_name_or_path "BAAI/bge-large-en" \
  --generator_name_or_path "meta-llama/Llama-2-7b-hf" \
  --output_dir "rag_e2e_checkpoints" \
  --per_device_train_batch_size 12
```

gets the error 
```
Special tokens file saved in rag_e2e_checkpoints/generator/special_tokens_map.json
Traceback (most recent call last):

  File "/workspace/ben/DALM/.venv/bin/dalm", line 8, in <module>
    sys.exit(cli())

  File "/workspace/ben/DALM/dalm/cli.py", line 128, in train_rag_e2e
    train_e2e(

  File "/workspace/ben/DALM/dalm/training/rag_e2e/train_rage2e.py", line 516, in train_e2e
    accelerator.end_training()

  File "/workspace/ben/DALM/.venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 615, in _inner
    return PartialState().on_main_process(function)(*args, **kwargs)

  File "/workspace/ben/DALM/.venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 2499, in end_training
    for tracker in self.trackers:

AttributeError: 'Accelerator' object has no attribute 'trackers'
```

because of https://github.com/huggingface/accelerate/pull/1994

**Comment by Ben-Epstein** [comment]
fixed by https://github.com/arcee-ai/DALM/commit/afdbeb5543bb0199524521a3c6e2b6897a34e375
