### ISSUE TITLE
Installation problem on main branch

### ISSUE THREAD

**Issue by tleyden** [arcee-ai/DALM#88]
If you clone the main branch and try to install, you will likely hit this error.

```
14.30  × Preparing metadata (pyproject.toml) did not run successfully.
14.30  │ exit code: 1
14.30  ╰─> [33 lines of output]
14.30    Traceback (most recent call last):
14.30     File "/opt/conda/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
14.30      main()
14.30     File "/opt/conda/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
14.30      json_out['return_val'] = hook(**hook_input['kwargs'])
14.30     File "/opt/conda/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
14.30      whl_basename = backend.build_wheel(metadata_directory, config_settings)
14.30     File "/tmp/pip-build-env-yo0q6xyo/overlay/lib/python3.10/site-packages/hatchling/build.py", line 58, in build_wheel
14.30      return os.path.basename(next(builder.build(directory=wheel_directory, versions=['standard'])))
14.30     File "/tmp/pip-build-env-yo0q6xyo/overlay/lib/python3.10/site-packages/hatchling/builders/plugin/interface.py", line 155, in build
14.30      artifact = version_api[version](directory, **build_data)
14.30     File "/tmp/pip-build-env-yo0q6xyo/overlay/lib/python3.10/site-packages/hatchling/builders/wheel.py", line 412, in build_standard
14.30      for included_file in self.recurse_included_files():
14.30     File "/tmp/pip-build-env-yo0q6xyo/overlay/lib/python3.10/site-packages/hatchling/builders/plugin/interface.py", line 176, in recurse_included_files
14.30      yield from self.recurse_selected_project_files()
14.30     File "/tmp/pip-build-env-yo0q6xyo/overlay/lib/python3.10/site-packages/hatchling/builders/plugin/interface.py", line 180, in recurse_selected_project_files
14.30      if self.config.only_include:
14.30     File "/tmp/pip-build-env-yo0q6xyo/overlay/lib/python3.10/site-packages/hatchling/builders/config.py", line 781, in only_include
14.30      only_include = only_include_config.get('only-include', self.default_only_include()) or self.packages
14.30     File "/tmp/pip-build-env-yo0q6xyo/overlay/lib/python3.10/site-packages/hatchling/builders/wheel.py", line 231, in default_only_include
14.30      return self.default_file_selection_options.only_include
14.30     File "/opt/conda/lib/python3.10/functools.py", line 981, in __get__
14.30      val = self.func(instance)
14.30     File "/tmp/pip-build-env-yo0q6xyo/overlay/lib/python3.10/site-packages/hatchling/builders/wheel.py", line 219, in default_file_selection_options
14.30      raise ValueError(message)
14.30    ValueError: Unable to determine which files to ship inside the wheel using the following heuristics: https://hatch.pypa.io/latest/plugins/builder/wheel/#default-file-selection
```

It should be fixed once https://github.com/arcee-ai/DALM/pull/86 is merged.

**Comment by tleyden** [comment]
Fixed in https://github.com/arcee-ai/DALM/pull/86
